### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by Hajiyor** [Am-Delta/xssh#2]
چطوری میشه از ربات بک اپ گرفت

**Comment by thezass** [comment]
فایل ssh.db و دانلود کنید از توی پوشه ی ربات اون اطلاعات دیتابیس ربات هستش

**Comment by Am-Delta** [comment]
کامند 
/backup
بزنید یا قسمت تنظیمات بکاپ > بکاپ ربات

یا 

> فایل ssh.db و دانلود کنید از توی پوشه ی ربات اون اطلاعات دیتابیس ربات هستش
